[workspace]
members = ["content", "shuttle", "shared", "fly", "webapp"]
resolver = "2"

[workspace.dependencies]
openai_dive = "0.3"
sqlx = { version = "0.7", features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
] }
pgvector = { version = "0.3", features = ["sqlx"] }
log = "0.4"
url = "2.5"
serde = { version = "1.0", features = ["derive"] }
axum = { version = "0.6", features = ["macros"] }
tokio = "1.28.2"
