[workspace]
members = ["content", "shared", "fly", "webapp"]
resolver = "2"

[workspace.dependencies]
openai_dive = "0.3.7"
sqlx = { version = "0.7.3", features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
] }
pgvector = { version = "0.3.2", features = ["sqlx"] }
log = "0.4.20"
url = { version = "2.5.0", features = ["serde"] }
serde = { version = "1.0.193", features = ["derive"] }
axum = { version = "0.7.3", features = ["macros"] }
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"] }
dotenvy = "0.15.7"
