app = 'fosdem2024-tika'
primary_region = 'iad'

[build]
image = 'apache/tika:2.9.1.0-full'

[http_service]
internal_port = 9998
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/tika"

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
