app = "fosdem2024"
primary_region = "lhr"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[env]
OTEL_DEPLOYMENT_ENVIRONMENT = "production"
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = "https://api.honeycomb.io/v1/traces"
