[package]
name = "webapp"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6", features = ["macros"] }
tokio = "1.28.2"
axum-valid = "0.11"
validator = { version = "0.16", features = ["derive"] }
askama = "0.12"
serde = { workspace = true }
shared = { path = "../shared" }
