[package]
name = "content"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["derive"] }
quick-xml = { version = "0.29", features = ["serialize"] }
xmlserde = "0.5"
xmlserde_derives = "0.5"
csv = "1.3"
openai_dive = "0.3"
tokio = { version = "1.35", features = ["rt-multi-thread", "macros"] }
dotenv = "0.15.0"
