[package]
name = "content"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["derive"] }
quick-xml = { version = "0.29", features = ["serialize"] }
xmlserde = "0.5"
xmlserde_derives = "0.5"
serde = { version = "1.0", features = ["derive"] }
csv = "1.3"
openai_dive = { workspace = true }
tokio = { version = "1.35", features = ["rt-multi-thread", "macros"] }
dotenvy = "0.15"
indicatif = "0.17"
sqlx = { version = "0.7", features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
] }
futures = "0.3"
log = "0.4"
env_logger = "0.10"
pgvector = { version = "0.3", features = ["sqlx"] }
url = "2.5"
shared = { path = "../shared" }
